package com.example.trucks_order.mapper;

import com.example.trucks_order.dataobject.ConnecDO;
import com.example.trucks_order.dataobject.OrderDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface OrderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    int insert(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    int insertSelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    OrderDO selectByPrimaryKey(Integer orderId);

    List<OrderDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    int updateByPrimaryKeySelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    int updateByPrimaryKey(OrderDO record);

    List<ConnecDO> selectByDriverId(Integer driverId);
}