package com.example.trucks_order.dataobject;

public class DriverDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_info.driver_id
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private Integer driverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_info.driver_name
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private String driverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_info.driver_sex
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private Integer driverSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_info.driver_age
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private Integer driverAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_info.idcard_img_path
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private String idcardImgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_info.driver_qual_img_path
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private String driverQualImgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_info.car_qual_img_path
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private String carQualImgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_info.car_insurance_img_path
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private String carInsuranceImgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_info.car_license_img_path
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private String carLicenseImgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column driver_info.password
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_info.driver_id
     *
     * @return the value of driver_info.driver_id
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_info.driver_id
     *
     * @param driverId the value for driver_info.driver_id
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_info.driver_name
     *
     * @return the value of driver_info.driver_name
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public String getDriverName() {
        return driverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_info.driver_name
     *
     * @param driverName the value for driver_info.driver_name
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setDriverName(String driverName) {
        this.driverName = driverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_info.driver_sex
     *
     * @return the value of driver_info.driver_sex
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public Integer getDriverSex() {
        return driverSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_info.driver_sex
     *
     * @param driverSex the value for driver_info.driver_sex
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setDriverSex(Integer driverSex) {
        this.driverSex = driverSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_info.driver_age
     *
     * @return the value of driver_info.driver_age
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public Integer getDriverAge() {
        return driverAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_info.driver_age
     *
     * @param driverAge the value for driver_info.driver_age
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setDriverAge(Integer driverAge) {
        this.driverAge = driverAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_info.idcard_img_path
     *
     * @return the value of driver_info.idcard_img_path
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public String getIdcardImgPath() {
        return idcardImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_info.idcard_img_path
     *
     * @param idcardImgPath the value for driver_info.idcard_img_path
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setIdcardImgPath(String idcardImgPath) {
        this.idcardImgPath = idcardImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_info.driver_qual_img_path
     *
     * @return the value of driver_info.driver_qual_img_path
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public String getDriverQualImgPath() {
        return driverQualImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_info.driver_qual_img_path
     *
     * @param driverQualImgPath the value for driver_info.driver_qual_img_path
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setDriverQualImgPath(String driverQualImgPath) {
        this.driverQualImgPath = driverQualImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_info.car_qual_img_path
     *
     * @return the value of driver_info.car_qual_img_path
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public String getCarQualImgPath() {
        return carQualImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_info.car_qual_img_path
     *
     * @param carQualImgPath the value for driver_info.car_qual_img_path
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setCarQualImgPath(String carQualImgPath) {
        this.carQualImgPath = carQualImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_info.car_insurance_img_path
     *
     * @return the value of driver_info.car_insurance_img_path
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public String getCarInsuranceImgPath() {
        return carInsuranceImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_info.car_insurance_img_path
     *
     * @param carInsuranceImgPath the value for driver_info.car_insurance_img_path
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setCarInsuranceImgPath(String carInsuranceImgPath) {
        this.carInsuranceImgPath = carInsuranceImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_info.car_license_img_path
     *
     * @return the value of driver_info.car_license_img_path
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public String getCarLicenseImgPath() {
        return carLicenseImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_info.car_license_img_path
     *
     * @param carLicenseImgPath the value for driver_info.car_license_img_path
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setCarLicenseImgPath(String carLicenseImgPath) {
        this.carLicenseImgPath = carLicenseImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column driver_info.password
     *
     * @return the value of driver_info.password
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column driver_info.password
     *
     * @param password the value for driver_info.password
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }
}