package com.example.trucks_order.dataobject;

import java.math.BigDecimal;

public class OrderDO {

    @Override
    public String toString() {
        return "OrderDO{" +
                "orderId=" + orderId +
                ", carType=" + carType +
                ", itemImgPath='" + itemImgPath + '\'' +
                ", itemVolume='" + itemVolume + '\'' +
                ", orderTime='" + orderTime + '\'' +
                ", orderTimeline='" + orderTimeline + '\'' +
                ", itemCount=" + itemCount +
                ", orderStartPosition='" + orderStartPosition + '\'' +
                ", orderEndPosition='" + orderEndPosition + '\'' +
                ", linkmanName='" + linkmanName + '\'' +
                ", linkmanTel='" + linkmanTel + '\'' +
                ", itemDesc='" + itemDesc + '\'' +
                ", price=" + price +
                ", status=" + status +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_id
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.car_type
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private Integer carType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.item_img_path
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private String itemImgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.item_volume
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private String itemVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_time
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private String orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_timeline
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private String orderTimeline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.item_count
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private Integer itemCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_start_position
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private String orderStartPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.order_end_position
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private String orderEndPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.linkman_name
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private String linkmanName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.linkman_tel
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private String linkmanTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.item_desc
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private String itemDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.price
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    private BigDecimal price;

    private Integer status;

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_id
     *
     * @return the value of order_info.order_id
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_id
     *
     * @param orderId the value for order_info.order_id
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.car_type
     *
     * @return the value of order_info.car_type
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public Integer getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.car_type
     *
     * @param carType the value for order_info.car_type
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setCarType(Integer carType) {
        this.carType = carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.item_img_path
     *
     * @return the value of order_info.item_img_path
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public String getItemImgPath() {
        return itemImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.item_img_path
     *
     * @param itemImgPath the value for order_info.item_img_path
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setItemImgPath(String itemImgPath) {
        this.itemImgPath = itemImgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.item_volume
     *
     * @return the value of order_info.item_volume
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public String getItemVolume() {
        return itemVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.item_volume
     *
     * @param itemVolume the value for order_info.item_volume
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setItemVolume(String itemVolume) {
        this.itemVolume = itemVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_time
     *
     * @return the value of order_info.order_time
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public String getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_time
     *
     * @param orderTime the value for order_info.order_time
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setOrderTime(String orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_timeline
     *
     * @return the value of order_info.order_timeline
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public String getOrderTimeline() {
        return orderTimeline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_timeline
     *
     * @param orderTimeline the value for order_info.order_timeline
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setOrderTimeline(String orderTimeline) {
        this.orderTimeline = orderTimeline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.item_count
     *
     * @return the value of order_info.item_count
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public Integer getItemCount() {
        return itemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.item_count
     *
     * @param itemCount the value for order_info.item_count
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setItemCount(Integer itemCount) {
        this.itemCount = itemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_start_position
     *
     * @return the value of order_info.order_start_position
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public String getOrderStartPosition() {
        return orderStartPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_start_position
     *
     * @param orderStartPosition the value for order_info.order_start_position
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setOrderStartPosition(String orderStartPosition) {
        this.orderStartPosition = orderStartPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.order_end_position
     *
     * @return the value of order_info.order_end_position
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public String getOrderEndPosition() {
        return orderEndPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.order_end_position
     *
     * @param orderEndPosition the value for order_info.order_end_position
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setOrderEndPosition(String orderEndPosition) {
        this.orderEndPosition = orderEndPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.linkman_name
     *
     * @return the value of order_info.linkman_name
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public String getLinkmanName() {
        return linkmanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.linkman_name
     *
     * @param linkmanName the value for order_info.linkman_name
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setLinkmanName(String linkmanName) {
        this.linkmanName = linkmanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.linkman_tel
     *
     * @return the value of order_info.linkman_tel
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public String getLinkmanTel() {
        return linkmanTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.linkman_tel
     *
     * @param linkmanTel the value for order_info.linkman_tel
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setLinkmanTel(String linkmanTel) {
        this.linkmanTel = linkmanTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.item_desc
     *
     * @return the value of order_info.item_desc
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public String getItemDesc() {
        return itemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.item_desc
     *
     * @param itemDesc the value for order_info.item_desc
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setItemDesc(String itemDesc) {
        this.itemDesc = itemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.price
     *
     * @return the value of order_info.price
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.price
     *
     * @param price the value for order_info.price
     *
     * @mbg.generated Tue Apr 09 14:54:21 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}